stages:
  - deploy

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"

deploy:
  stage: deploy
  tags:
    - docker
  image: ubuntu:cicd
  before_script:
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
  script:
    - ssh z@$SSH_HOST "cd $WORK_DIR && git pull http://gitlab+deploy-token-2:2APXvdxHcz3Xgzy3weaE@git.ft/doc/documents && docker compose up --build -d && exit"
  after_script:
    - rm -rf ~/.ssh
