site_name: آموزش ها

theme:
  name: 'material'
  language: 'fa'
  direction: 'rtl'
  palette:
    primary: 'green'
    accent: 'blue'
  font: false
  feature:
    tabs: false
    
  features:
    - search.suggest
    - search.highlight
    - navigation.top
    - content.code.copy
    - content.action.edit  
    
    
  # extra:
  #   social:
  #     - type: 'github'
  #       link: 'https://github.com/squidfunk'    

extra_css:
  - 'stylesheets/extra.css'
  #- CSS/pdf.css

nav:
- صفحه اصلی: 'index.md'
- آموزش گیت: 'page-git.md'
- آموزش داکر: 'page-docker.md'
- اجایل: 'page-agile.md'
- دواپس: 'page-devops.md'
- کوبرنتیز: 'page-kubernetes.md'
#- بخش دو: 'sec2.md'

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.blocks.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.tab    
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.blocks.html    
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.progressbar
  - toc:
      permalink: 🔗
      # title: On this page
      permalink_title: Link here

plugins:
    - search:
        indexing: 'full'
          #    - pdf-export:
          #        verbose: true
          #        media_type: print
    - glightbox:
        zoomable: true

repo_url: http://git.ft/doc/documents
edit_uri: edit/main/docs/
